version: 2

models:
  - name: stg_nyc_taxi_train
    description: "Nossa camada 'Refined' (Prata). Limpa e renomeia colunas da tabela raw. Remove viagens com 0 passageiros."
    columns:
      - name: id_viagem
        description: "A chave primária única para cada viagem."
        tests:
          - unique
          - not_null

  - name: business_total_viagens_por_fornecedor
    description: "Nossa camada 'Business' (Ouro). Agrega métricas de viagem por fornecedor (vendor_id)."
    columns:
      - name: id_fornecedor
        description: "O ID do fornecedor (1 ou 2)."
        tests:
          - unique
          - not_null